/*
 * The hast property-name table, from the source of truth.
 *
 * mdy-docs resolves an HTML attribute name through `property-information`'s
 * `find(html, name)`, so this parser has to agree with that library and not
 * with a plausible summary of it. Hand-written, the table was twenty entries
 * and wrong about `SRC` (case), `FOO` (kept verbatim, not lowercased) and
 * `DATA-x-Y` (only the first dash camel-cases). Generated, it is all 426.
 *
 *   node scripts/generate_props.mjs <path-to-mdy-docs> > src/props_table.h
 *
 * The path is where `property-information` is installed; this repo does not
 * depend on it, and the table is checked in so a build never needs node.
 *
 * Two tables come out of it, one per direction:
 *
 *   MDY_PROPS      normalized attribute name -> hast property name, for
 *                  PARSING, where the author wrote the attribute.
 *   MDY_PROP_INFO  hast property name -> the attribute to write, plus the
 *                  three flags serialisation needs (boolean, overloaded
 *                  boolean, comma-separated), for WRITING.
 *
 * Both sorted by their key so the lookups can bisect.
 */
const base = process.argv[2];
if (!base) throw new Error('usage: generate_props.mjs <dir containing node_modules/property-information>');
const { html } = await import(
  new URL('node_modules/property-information/index.js', `file://${base.replace(/\/?$/, '/')}`)
);

const rows = [...new Set(Object.keys(html.normal))]
  .map((normal) => [normal, html.normal[normal]])
  .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));

const esc = (s) => s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');

/* property -> attribute, and the flags that change how a value is written. */
const info = Object.entries(html.property)
  .map(([property, i]) => [
    property,
    i.attribute,
    (i.boolean ? 1 : 0) | (i.overloadedBoolean ? 2 : 0) | (i.commaSeparated ? 4 : 0),
  ])
  .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));

process.stdout.write(`/* Generated by scripts/generate_props.mjs — do not edit.
 * ${rows.length} attribute names and ${info.length} properties from
 * property-information's html schema. */
#ifndef MDY_PROPS_TABLE_H
#define MDY_PROPS_TABLE_H

/* Parsing: the attribute an author wrote -> the hast property it becomes. */
static const struct { const char *normal; const char *property; } MDY_PROPS[] = {
${rows.map(([n, p]) => `    { "${esc(n)}", "${esc(p)}" },`).join('\n')}
};
#define MDY_PROPS_COUNT ${rows.length}

/* Writing: the hast property -> the attribute to write, and its flags.
 * 1 = boolean, 2 = overloaded boolean, 4 = comma-separated. */
#define MDY_ATTR_BOOLEAN     1
#define MDY_ATTR_OVERLOADED  2
#define MDY_ATTR_COMMAS      4

static const struct { const char *property; const char *attribute; unsigned flags; } MDY_PROP_INFO[] = {
${info.map(([p, a, f]) => `    { "${esc(p)}", "${esc(a)}", ${f} },`).join('\n')}
};
#define MDY_PROP_INFO_COUNT ${info.length}

#endif
`);
