/*
 * The sanitize schema, from the source of truth.
 *
 *   node scripts/generate_schema.mjs <path-to-mdy-docs> > src/schema_table.h
 *
 * Transcribing it by hand produced a subset that was wrong in both directions:
 * `time`'s `datetime` was missing, and the whole `strip` list was absent — so
 * an element that should be dropped WITH its content was instead treated like
 * any other disallowed one. The two rules are not the same:
 *
 *   - a tag in `strip` disappears, and everything indented under it with it;
 *   - a tag merely absent from `tagNames` becomes a <div> and KEEPS its
 *     content, with its attributes still judged by the name the author wrote.
 *
 * The two regex rules (`aria-`, `data-`) stay as code in attrs.c; everything
 * else is a sorted table here so the lookups can bisect.
 */
const base = process.argv[2];
if (!base) throw new Error('usage: generate_schema.mjs <path to mdy-docs>');
const { defaultSchema: s } = await import(
  new URL('src/parse/sanitize.js', `file://${base.replace(/\/?$/, '/')}`)
);

const sorted = (a) => [...a].sort();
const list = (name, values) =>
  `static const char *const ${name}[] = {\n${sorted(values)
    .map((v) => `    "${v}",`)
    .join('\n')}\n};\n#define ${name}_COUNT ${values.length}\n`;

/* {tag, attr} pairs, sorted by tag then attr. "*" is the global set. */
const pairs = [];
for (const [tag, rules] of Object.entries(s.attributes)) {
  for (const rule of rules) if (typeof rule === 'string') pairs.push([tag, rule]);
}
pairs.sort((a, b) => (a[0] === b[0] ? (a[1] < b[1] ? -1 : 1) : a[0] < b[0] ? -1 : 1));

const protocols = [];
for (const [attr, list_] of Object.entries(s.protocols)) {
  for (const p of list_) protocols.push([attr, p]);
}
protocols.sort((a, b) => (a[0] === b[0] ? (a[1] < b[1] ? -1 : 1) : a[0] < b[0] ? -1 : 1));

process.stdout.write(`/* Generated by scripts/generate_schema.mjs — do not edit. */
#ifndef MDY_SCHEMA_TABLE_H
#define MDY_SCHEMA_TABLE_H

/* Elements an author may open. Anything else becomes a <div>. */
${list('MDY_TAG_NAMES', s.tagNames)}
/* Elements removed outright, along with everything indented under them. */
${list('MDY_STRIP', s.strip)}
/* Allowed attributes per tag; "*" applies to every element. The two regex
 * rules in the schema (aria-, data-) are handled in code. */
static const struct { const char *tag; const char *attr; } MDY_TAG_ATTRS[] = {
${pairs.map(([t, a]) => `    { "${t}", "${a}" },`).join('\n')}
};
#define MDY_TAG_ATTRS_COUNT ${pairs.length}

/* An attribute listed here may carry only a relative URL or one of these. */
static const struct { const char *attr; const char *protocol; } MDY_PROTOCOLS[] = {
${protocols.map(([a, p]) => `    { "${a}", "${p}" },`).join('\n')}
};
#define MDY_PROTOCOLS_COUNT ${protocols.length}

#endif
`);
