/*
 * The hast property-name table, from the source of truth.
 *
 * mdy-docs resolves an HTML attribute name through `property-information`'s
 * `find(html, name)`, so this parser has to agree with that library and not
 * with a plausible summary of it. Hand-written, the table was twenty entries
 * and wrong about `SRC` (case), `FOO` (kept verbatim, not lowercased) and
 * `DATA-x-Y` (only the first dash camel-cases). Generated, it is all 426.
 *
 *   node scripts/generate_props.mjs <path-to-mdy-docs> > src/props_table.h
 *
 * The path is where `property-information` is installed; this repo does not
 * depend on it, and the table is checked in so a build never needs node.
 *
 * Sorted by the normalized (lowercased) name so the lookup can bisect.
 */
const base = process.argv[2];
if (!base) throw new Error('usage: generate_props.mjs <dir containing node_modules/property-information>');
const { html } = await import(
  new URL('node_modules/property-information/index.js', `file://${base.replace(/\/?$/, '/')}`)
);

const rows = [...new Set(Object.keys(html.normal))]
  .map((normal) => [normal, html.normal[normal]])
  .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));

const esc = (s) => s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');

process.stdout.write(`/* Generated by scripts/generate_props.mjs — do not edit.
 * ${rows.length} names from property-information's html schema. */
#ifndef MDY_PROPS_TABLE_H
#define MDY_PROPS_TABLE_H

static const struct { const char *normal; const char *property; } MDY_PROPS[] = {
${rows.map(([n, p]) => `    { "${esc(n)}", "${esc(p)}" },`).join('\n')}
};
#define MDY_PROPS_COUNT ${rows.length}

#endif
`);
