/*
 * Generate src/emoji_table.h from the packages mdy-docs uses.
 *
 * `emoticon` and `gemoji` are data, not behaviour, and copying data by hand is
 * how it drifts. This reads the same two packages the JavaScript imports and
 * emits a C table, so regenerating after an upgrade is one command rather than
 * an afternoon.
 *
 *   node scripts/generate_emoji.mjs <path to mdy-docs> > src/emoji_table.h
 *
 * The path is required because the packages live in mdy-docs' node_modules,
 * not this repo's — this one has no package.json at all, and adding one to
 * pull two data packages would be a heavier dependency than the generated
 * header it produces.
 *
 * Both tables come out sorted, so the lookups can be binary searches.
 */
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
import { join } from 'node:path';

const mdyDocs = process.argv[2];
if (!mdyDocs) {
  console.error('usage: generate_emoji.mjs <path to mdy-docs>');
  process.exit(2);
}
const require = createRequire(pathToFileURL(join(mdyDocs, 'package.json')));
const { emoticon } = await import(pathToFileURL(require.resolve('emoticon')));
const { nameToEmoji } = await import(pathToFileURL(require.resolve('gemoji')));

/*
 * THREE-DIGIT OCTAL, not hex. A C hex escape is greedy — `\x22D` is one
 * (invalid) escape rather than `"` followed by `D` — and several emoticons are
 * exactly that shape: `:"D` is one of them. An octal escape takes at most
 * three digits, so it always ends where it should.
 */
const cString = (s) =>
  '"' + [...Buffer.from(s, 'utf8')].map((b) =>
    b >= 0x20 && b < 0x7f && b !== 0x22 && b !== 0x5c && b !== 0x3f
      ? String.fromCharCode(b)
      : '\\' + b.toString(8).padStart(3, '0')
  ).join('') + '"';

const emoticons = new Map();
for (const entry of emoticon) {
  for (const value of entry.emoticons) emoticons.set(value, entry.emoji);
}
const longest = Math.max(...[...emoticons.keys()].map((k) => k.length));

const out = [];
out.push('/*');
out.push(' * GENERATED by scripts/generate_emoji.mjs — do not edit.');
out.push(' *');
out.push(' * The same data mdy-docs gets from the `emoticon` and `gemoji` packages, so');
out.push(' * `:rocket:` and `:)` mean here what they mean there. Regenerate after');
out.push(' * upgrading either package.');
out.push(' */');
out.push('#ifndef MDY_EMOJI_TABLE_H');
out.push('#define MDY_EMOJI_TABLE_H');
out.push('');
out.push('typedef struct { const char *key; const char *emoji; } MdyEmoji;');
out.push('');
out.push(`#define MDY_EMOTICON_LONGEST ${longest}`);
out.push('');
out.push('/* Which ASCII characters an emoticon can START with. The JavaScript keeps');
out.push(' * the same set and for the same reason: without it, every position in every');
out.push(' * document pays for a table search that almost always fails. */');
const openers = new Set([...emoticons.keys()].map((k) => k.charCodeAt(0)));
out.push('static const unsigned char MDY_EMOTICON_OPENER[128] = {');
for (let row = 0; row < 8; row++) {
  out.push('    ' + Array.from({ length: 16 }, (_, i) => (openers.has(row * 16 + i) ? '1' : '0')).join(',') + ',');
}
out.push('};');
out.push('');
out.push('/* `:)` and its friends. Sorted by key, for a binary search. */');
out.push('static const MdyEmoji MDY_EMOTICONS[] = {');
for (const [k, v] of [...emoticons].sort((a, b) => (a[0] < b[0] ? -1 : 1))) {
  out.push(`    { ${cString(k)}, ${cString(v)} },`);
}
out.push('};');
out.push('');
out.push('/* GitHub shortcode names, without the colons. Sorted by key. */');
out.push('static const MdyEmoji MDY_SHORTCODES[] = {');
for (const [k, v] of Object.entries(nameToEmoji).sort((a, b) => (a[0] < b[0] ? -1 : 1))) {
  out.push(`    { ${cString(k)}, ${cString(v)} },`);
}
out.push('};');
out.push('');
out.push('#endif');
console.log(out.join('\n'));
